### ISSUE TITLE
(pcsx2.portable) Portable version not actually portable anymore

### ISSUE THREAD

**Issue by opusforlife2** [TheCakeIsNaOH/chocolatey-packages#35]
## Expected Behavior

The portable version of the package must create an empty portable.ini file in the root folder, as mentioned here: https://pcsx2.net/docs/post/general/#portable-mode

This happened automatically for 1.6.0, but not for 2.0.2.

## Current Behavior

This file is missing, so PCSX2 went ahead and created all its files in the default location. I don't know what changed from version 1.6.0, but this file needs to be created upon installation. It can be created manually, but any update to the package might wipe it again.

**Comment by TheCakeIsNaOH** [comment]
I hadn't noticed this behavior, since my installations have been upgraded from 1.6.0.

What is your option on having this file created automatically vs having it controlled with a package parameter? That way, users could use the portable version but still have their user-level config/save files, which may be useful for someone with a non-administrative install of Chocolatey. But this is a breaking change in the software, which the package could ameliorate.

**Comment by TheCakeIsNaOH** [comment]
I have not had time to look into this further, I'll try to get to it soon.
